/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'customerName' : string,
  'status' : BookingStatus,
  'paymentStatus' : PaymentStatus,
  'customer' : Principal,
  'scheduledDate' : string,
  'scheduledTime' : string,
  'address' : string,
  'serviceId' : bigint,
  'phone' : string,
  'providerId' : [] | [bigint],
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null } |
  { 'inProgress' : null };
export interface Location { 'latitude' : number, 'longitude' : number }
export type PaymentStatus = { 'paid' : null } |
  { 'unpaid' : null } |
  { 'failed' : null };
export interface Provider {
  'id' : bigint,
  'serviceType' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'rating' : number,
  'totalReviews' : bigint,
  'location' : Location,
}
export interface Rating {
  'bookingId' : bigint,
  'comment' : string,
  'rating' : bigint,
  'providerId' : bigint,
}
export interface Service {
  'id' : bigint,
  'icon' : string,
  'name' : string,
  'description' : string,
  'estimatedDuration' : bigint,
  'basePrice' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProvider' : ActorMethod<[string, bigint], bigint>,
  'addService' : ActorMethod<[string, string, string, bigint, bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmPayment' : ActorMethod<[bigint, string], undefined>,
  'createBooking' : ActorMethod<
    [bigint, string, string, string, string, string],
    bigint
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createPaymentSession' : ActorMethod<[bigint, bigint, string], string>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllProviders' : ActorMethod<[], Array<Provider>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getBooking' : ActorMethod<[bigint], Booking>,
  'getBookingPaymentStatus' : ActorMethod<[bigint], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProvider' : ActorMethod<[bigint], Provider>,
  'getProviderLocation' : ActorMethod<[bigint], Location>,
  'getProviderRatings' : ActorMethod<[bigint], Array<Rating>>,
  'getService' : ActorMethod<[bigint], Service>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserBookings' : ActorMethod<[], Array<Booking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitRating' : ActorMethod<[bigint, bigint, bigint, string], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateProviderLocation' : ActorMethod<[bigint, number, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];